---
title: "Untitled"
author: "Chaoqi Wu"
date: "2023-08-08"
output: html_document
---

```{r setup, include=FALSE}
library(MXM)
library(rje)
library(tidyverse)
library(arules)
library(caret)
library(BB)
library(ranger)
library(randomForest)
library(caret)
```

```{r}
time1 <- Sys.time()


result_cb2 <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  # simulate the original dataset
  L1 <- runif(n,0,1)
  L2 <- runif(n,0,1)
  L3 <- runif(n,0,1)
  L_vec <- tibble(
    L1 = L1,
    L2 = L2,
    L3 = L3)
  L_vec <- L_vec %>% 
    mutate(
      length = (L1^2 + L2^2 + L3^2)^0.5,
      L1 = L1/length,
      L2 = L2/length,
      L3 = L3/length
      ) %>% 
    select(-length)
  L.true <- 2*L1 + L2^2 + L1*L3
  Z <- 0.5 + 0.5*L.true
  pr <- 1/(1+3.5*exp(-Z)) # control the probability close to 0.5
  Y.true <- 2*Z - rnorm(n)
  A.true <- rbinom(n,1,pr)
  dat <- tibble(
    Y = Y.true,
    A = A.true
  ) %>% cbind(L_vec)
  # get the parameter that we are interested
  result_cb2[i,1] <- exp(psi.hat_ranger(dat$Y,dat$A,L=c(), subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE))
  result_cb2[i,3] <- exp(psi.hat_ranger(dat$Y,dat$A,L_vec, subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE))
  # boostrap preparation
  result <- matrix(ncol = 2,nrow = nboots)
  
  for (j in 1:nboots) {
    # simulate each bootstrap
    n <- dim(dat)[1]
    set.seed(j)
    indb1 <- sample(1:n, size = n, replace = TRUE)
    datj <-  dat[indb1,]
    L <- tibble(L = datj$L)
    # parameter in bootrap
    result[j,1] <- psi.hat_ranger(datj$Y,datj$A,L=c(), subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE)
    result[j,2] <- psi.hat_ranger(datj$Y,datj$A,L_vec, subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE)
  }
  result_cb2[i,2] <- sd(result[,1])
  result_cb2[i,4] <- sd(result[,2])
}

# result
res_cb2 <- as.data.frame(result_cb2[,1:4])

colnames(res_cb2) <- c("point","sd","point_L","sd_L")
res_cb2 <- res_cb2 %>% 
  mutate(
    ci_low   = point - 1.96*sd,
    ci_high  = point + 1.96*sd,
    ci_low_L   = point_L - 1.96*sd_L,
    ci_high_L  = point_L + 1.96*sd_L
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

table_cb2 <- tibble(
  noL <- c(sum(res_cb2$contain)/nrow(res_cb2)),
  L <- c(sum(res_cb2$contain_L)/nrow(res_cb2))
  )

knitr::kable(table_cb2,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Continuous Outcome to Binary Exposure"
             ) 
time2 <- Sys.time()
time2-time1
```

