---
title: "odds ratio test"
author: "Daniel Malinsky and Chaoqi Wu"
date: "2023-03-26"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
    code_folding: hide
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhead[R]{\thepage}
- \fancypagestyle{plain}{\pagestyle{fancy}}
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(MXM)
library(rje)
library(tidyverse)
library(arules)
library(caret)
library(BB)
```

# Simulate Data

```{r}
# from continous to binary
c_to_b <- function(z,n){
  b <- expit(0.5+z)
  y <- rbinom(n,1,b)
  return(y)
}


# from continous to ordinal
c_to_o <- function(z,n,cate){
  z <- z + rnorm(n)
  y <- discretize(z, breaks = cate)
  y <- factor(y,levels = levels(y),labels = c(1:cate))
  return(y)
}

# from continous to multinominal
c_to_multi <- function(z,n,class){
  y <- c()
  for (j in 1:n) {
    prob <- c()
    for (i in 1:class) {
      intercept <- rnorm(1)
      prob[i] <- expit(intercept+z[j])
    }
    x <- rmultinom(1,1,prob)
    for (k in 1:class) {
      if (x[,1][k]==1) {
      y[j] <- k
    }
    }
  }

  return(y)
}
```


# Estimation 
```{r}
# psi.hat <- function(Y, A, L=c(), subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = FALSE){
#   ## Function: estimate the odds ratio parameter psi
#   ## Input: 1. An outcome nuisance model, onm = f(Y|L,A=0)
#   ##        2. An exposure nuisance model, enm = g(A|Y=0,L)
#   ## Output: A real number (vector) psi.hat, an estimate of the conditional odds ratio parameter psi
#   
#   ## Todo: generalize estimating eq to arbitrary dimensions
#   
#   if(length(L)==0){
#     L <- cbind(rep(0,length(Y)),rep(0,length(Y))) ## for cases where conditioning set is empty
#     colnames(L) <- c("L1","L2")
#   }
#   
#   
#   if(!is.null(subset)) Y <- Y[subset]
#   if(!is.null(subset)) A <- A[subset,]
#   if(!is.null(subset)) L <- L[subset,]
#   #temp
#   
#   refA <- 0 
#   refY <- 0
# 
#     
#     if(out.bin && exp.bin){
#       h.dag <- 0.25 ## probability f.dag(Y|L) = g.dag(A|L) = 0.5, i.e., Y ~ A ~ Bernoulli(0.5)
#     
#       if(length(L)==0) {outcome <- glm(Y~A,family=binomial)} else outcome <- glm(Y ~ A + L, family = binomial)
#       dat1 <- data.frame(cbind(A,L))
#       dat1[,1] <- 0 ## setting A=0
#       onm <- predict.glm(outcome, newdata=dat1,type="response") # may cause warning: prediction from a rank-deficient fit may be misleading
#       onm[Y==0] <- 1-onm[Y==0]
#     
#       exposure <- glm(A ~ Y + L, family = binomial)
#       dat2 <- data.frame(cbind(Y,L))
#       dat2[,1] <- 0 ## setting Y=0
#       enm <- predict.glm(exposure, newdata=dat2,type="response") # may cause warning: prediction from a rank-deficient fit may be misleading
#       enm[A==0] <- 1-enm[A==0]
#     
#       d.diff <- (-1)^(Y+A) ## Eric's suggestion, for Y,A binary
#     
#       U <- function(psi,onm,enm,d.diff){ sum( d.diff*h.dag / (exp(psi*Y*A)*onm*enm) ) }
#       est <- uniroot(U, interval = c(-3.0, 3.0), extendInt = "yes", tol = 0.001, onm = onm, enm = enm, d.diff=d.diff)
#       return(est$root)
#     }
#   
#     if(!out.bin){ 
#       outcome <- glm(Y ~ A + L, family = gaussian)
#     } else outcome <- glm(Y ~ A + L, family = binomial)
#     dat1 <- data.frame(cbind(A,L))
#     dat1[,1] <- 0 ## setting A=0
#     onm <- predict.glm(outcome, newdata=dat1,type="response")
#     onm[Y==0] <- 1-onm[Y==0]
#   
#     if(!exp.bin){
#       exposure <- glm(A ~ Y + L, family = gaussian)
#     } else exposure <- glm(A ~ Y + L, family = binomial)
#     dat2 <- data.frame(cbind(Y,L))
#     dat2[,1] <- 0 ## setting Y=0
#     enm <- predict.glm(exposure, newdata=dat2,type="response")
#     enm[A==0] <- 1-enm[A==0]
#   
#   
#     #U <- function(psi,onm,enm){ sum( (Y - onm)*(A - enm)*exp(-psi*Y*A) )}
#     #est <- uniroot(U, interval = c(-3.0, 3.0), extendInt = "yes", tol = 0.001, onm = onm, enm = enm)
#     #return(est$root)
#   
#     U <- function(psi){ sum( (Y - onm)*(A - enm)*exp(-psi*Y*A) )}
#     par.init <- c(1.0)
#     sol <- BBsolve(par=par.init, fn=U, quiet=TRUE) 
#     est <- sol$par
#   
#     return(est)
# 
# 
#   
# }
```

```{r}
psi.hat <- function(Y, A, L=c(), subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = FALSE){
  ## Function: estimate the odds ratio parameter psi
  ## Input: 1. An outcome nuisance model, onm = f(Y|L,A=0)
  ##        2. An exposure nuisance model, enm = g(A|Y=0,L)
  ## Output: A real number (vector) psi.hat, an estimate of the conditional odds ratio parameter psi
  
  ## Todo: generalize estimating eq to arbitrary dimensions
  
  if(length(L)==0){
    fm_out <- "Y ~ A"
    fm_out <- as.formula(fm_out)
    fm_exp <- "A ~ Y"
    fm_exp <- as.formula(fm_exp) ## for cases where conditioning set is empty
    dat <- data.frame(Y,A)
  }else{
    covnames <- colnames(L)
    fm_out <- paste0("Y ~ A + ", paste(covnames, collapse = "+"))
    fm_out <- as.formula(fm_out)
    fm_exp <- paste0("A ~ Y + ", paste(covnames, collapse = "+"))
    fm_exp <- as.formula(fm_exp)
    dat <- data.frame(Y,A,L)
  }
  
  
  if(!is.null(subset)) Y <- Y[subset]
  if(!is.null(subset)) A <- A[subset,]
  if(!is.null(subset)) L <- L[subset,]
  #temp
  
  
  refA <- 0 
  refY <- 0
    
    if(out.bin && exp.bin){
      h.dag <- 0.25 ## probability f.dag(Y|L) = g.dag(A|L) = 0.5, i.e., Y ~ A ~ Bernoulli(0.5)
      dat1 <- dat
      dat2 <- dat
      
      outcome <- glm(fm_out,family=binomial,data = dat)
      dat1$A <- 0 ## setting A=0
      onm <- predict.glm(outcome, newdata=dat1,type="response") # may cause warning: prediction from a rank-deficient fit may be misleading
      onm[Y==0] <- 1-onm[Y==0]
    
      exposure <- glm(fm_exp, family = binomial,data = dat)
      dat2$Y <- 0 ## setting Y=0
      enm <- predict.glm(exposure, newdata=dat2,type="response") # may cause warning: prediction from a rank-deficient fit may be misleading
      enm[A==0] <- 1-enm[A==0]
    
      d.diff <- (-1)^(Y+A) ## Eric's suggestion, for Y,A binary
    
      U <- function(psi,onm,enm,d.diff){ sum( d.diff*h.dag / (exp(psi*Y*A)*onm*enm) ) }
      est <- uniroot(U, interval = c(-3.0, 3.0), extendInt = "yes", tol = 0.001,maxiter=1000, onm = onm, enm = enm, d.diff=d.diff)
      return(est$root)
    }
  
    if(!out.bin){ 
      outcome <- glm(fm_out, family = gaussian,data = dat)
    } else outcome <- glm(fm_out, family = binomial,data = dat)
    dat1 <- dat
    dat1$A <- 0 ## setting A=0
    onm <- predict.glm(outcome, newdata=dat1,type="response")
    onm[Y==0] <- 1-onm[Y==0]
  
    if(!exp.bin){
      exposure <- glm(fm_exp, family = gaussian,data = dat)
    } else exposure <- glm(fm_exp, family = binomial,data = dat)
    dat2 <- dat
    dat2$Y <- 0 ## setting Y=0
    enm <- predict.glm(exposure, newdata=dat2,type="response")
    enm[A==0] <- 1-enm[A==0]
  
  
    #U <- function(psi,onm,enm){ sum( (Y - onm)*(A - enm)*exp(-psi*Y*A) )}
    #est <- uniroot(U, interval = c(-3.0, 3.0), extendInt = "yes", tol = 0.001, onm = onm, enm = enm)
    #return(est$root)
  
    U <- function(psi){ sum( (Y - onm)*(A - enm)*exp(-psi*Y*A) )}
    par.init <- c(1.0)
    sol <- BBsolve(par=par.init, fn=U, quiet=TRUE) 
    est <- sol$par
  
    return(est)

}
```


# Function test   

```{r}
n <- 1000
nsample <- 10
nboots <- 5
```

## (1) outcome: continuous, exposure: binary
```{r}
result_cb <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  z <- rnorm(1000)
  y <- 2*z + rnorm(1000)
  x <- c_to_b(-2*z,1000)

  dat <- tibble(
    z = z,
    y = y,
    x = x
  )
  # summary(glm(y~x+z,data=dat))
  # summary(glm(y~x,data=dat))
  z <- tibble(L = dat$z)
  result_cb[i,1] <- exp(psi.hat(dat$y,dat$x,L=c(), subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE))
  result_cb[i,3] <- exp(psi.hat(dat$y,dat$x,z, subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE))
  result <- matrix(ncol = 2,nrow = nboots)
  for (j in 1:nboots) {
     n <- dim(dat)[1]
     set.seed(j)
     indb1 <- sample(1:n, size = n, replace = TRUE)
     datj <-  dat[indb1,]
     z <- tibble(z= datj$z)
     result[j,1] <- psi.hat(datj$y,datj$x,L=c(), subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE)
     result[j,2] <- psi.hat(datj$y,datj$x,z, subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE)
  }
  result_cb[i,2] <-   sd(exp(result[,1]))
  result_cb[i,4] <-   sd(exp(result[,2]))
}
res_cb <- as.data.frame(result_cb)

colnames(res_cb) <- c("point","sd","point_L","sd_L")

res_cb <- res_cb %>%
  mutate(
    ci_low     = point - 1.96*sd,
    ci_high    = point + 1.96*sd,
    ci_low_L   = point_L - 1.96*sd_L,
    ci_high_L  = point_L + 1.96*sd_L
  ) %>%
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>%
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

table_cb <- tibble(
  noL <- c(sum(res_cb$contain)/nrow(res_cb)),
  L <- c(sum(res_cb$contain_L)/nrow(res_cb))
  )

knitr::kable(table_cb,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Continuous Outcome to Binary Exposure"
             )
```

```{r}
result_cb2 <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  L.true <- rbinom(n,1,0.5) ## L.true <- cbind(L.true,rep(0,N))
  Z <- 0.5 + 0.5*L.true
  pr <- 1/(1+exp(-Z))
  Y.true <- 2*Z + rnorm(n)
  A.true <- rbinom(n,1,pr)
  dat <- tibble(
    L = L.true,
    Y = Y.true,
    A = A.true
  )
  # summary(glm(Y~A+L,data=dat))
  # summary(glm(Y~A,data=dat))
  L <- tibble(L = dat$L)
  result_cb2[i,1] <- exp(psi.hat(dat$Y,dat$A,L=c(), subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE))
  result_cb2[i,3] <- exp(psi.hat(dat$Y,dat$A,L, subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE))
  result <- matrix(ncol = 2,nrow = nboots)
  for (j in 1:nboots) {
    n <- dim(dat)[1]
    set.seed(j)
    indb1 <- sample(1:n, size = n, replace = TRUE)
    datj <-  dat[indb1,]
    L <- tibble(L = datj$L)
    result[j,1] <- psi.hat(datj$Y,datj$A,L=c(), subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE)
    result[j,2] <- psi.hat(datj$Y,datj$A,L, subset = NULL, out.bin = FALSE, exp.bin = TRUE, exp.scalar = TRUE)
  }
  result_cb2[i,2] <- sd(result[,1])
  result_cb2[i,4] <- sd(result[,2])
}

res_cb2 <- as.data.frame(result_cb2[,1:4])

colnames(res_cb2) <- c("point","sd","point_L","sd_L")
res_cb2 <- res_cb2 %>% 
  mutate(
    ci_low   = point - 1.96*sd,
    ci_high  = point + 1.96*sd,
    ci_low_L   = point_L - 1.96*sd_L,
    ci_high_L  = point_L + 1.96*sd_L
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

table_cb2 <- tibble(
  noL <- c(sum(res_cb2$contain)/nrow(res_cb2)),
  L <- c(sum(res_cb2$contain_L)/nrow(res_cb2))
  )

knitr::kable(table_cb2,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Continuous Outcome to Binary Exposure"
             ) 
```

## (2) outcome: continous, exposure: continous
```{r}
# z <- rnorm(1000)
# y <- -1.5*z - rnorm(1000)
# x <- 2*z + rnorm(1000)
# psi.hat(Y=y,A=x,L=c(), subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE)
# z <- tibble(z=z)
# psi.hat(y,x,z, subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE)

result_cc <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  z <- rnorm(1000)
  y <- 5*z + rnorm(1000)
  x <- -5*z - rnorm(1000)
  
  dat <- tibble(
    z = z,
    y = y,
    x = x
  )
  # summary(glm(y~x+z,data=dat))
  # summary(glm(y~x,data=dat))
  z <- tibble(z= dat$z)
  tryCatch(
           {
      result_cc[i,1] <- exp(psi.hat(dat$y,dat$x,L=c(), subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE))
      result_cc[i,3] <- exp(psi.hat(dat$y,dat$x,z, subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE))
      }, error=function(e){})
 
  result <- matrix(ncol = 2,nrow = nboots)
  for (j in 1:nboots) {
     n <- dim(dat)[1]
     indb1 <- sample(1:n, size = n, replace = TRUE)
     set.seed(j)
     datj <-  dat[indb1,]
     z <- tibble(z= datj$z)
       tryCatch(
           {
     result[j,1] <- psi.hat(datj$y,datj$x,L=c(), subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE)
     result[j,2] <- psi.hat(datj$y,datj$x,z, subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE)
           }, error=function(e){})
  }
  result_cc[i,2] <-   sd(exp(result[,1]))
  result_cc[i,4] <-   sd(exp(result[,2]))
}

res_cc <- as.data.frame(result_cc)

colnames(res_cc) <- c("point","sd","point_L","sd_L")
res_cc <- res_cc %>% 
  mutate(
    ci_low     = point - 1.96*sd,
    ci_high    = point + 1.96*sd,
    ci_low_L   = point_L - 1.96*sd_L,
    ci_high_L  = point_L + 1.96*sd_L
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

table_cc <- tibble(
  noL <- c(sum(res_cc$contain)/nrow(res_cc)),
  L <- c(sum(res_cc$contain_L)/nrow(res_cc))
  )

  

knitr::kable(table_cc,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Continuous Outcome to Continuous Exposure"
             )

```

```{r}
result_cc2 <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  L.true <- rnorm(n,0,1) ## L.true <- cbind(L.true,rep(0,N))
  Z <- 0.5 + 0.5*L.true
  Y.true <- 5*Z + rnorm(n)
  A.true <- -5*Z - rnorm(n)
  dat <- tibble(
    L = L.true,
    Y = Y.true,
    A = A.true
  )
  # summary(glm(Y~A+L,data=dat))
  # summary(glm(Y~A,data=dat))
  L <- tibble(L= dat$L)
  result_cc2[i,1] <- exp(psi.hat(dat$Y,dat$A,L=c(), subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE))
  result_cc2[i,3] <- exp(psi.hat(dat$Y,dat$A,L, subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE))
  result <- matrix(ncol = 2,nrow = nboots)
  for (j in 1:nboots) {
    n <- dim(dat)[1]
    set.seed(j)
    indb1 <- sample(1:n, size = n, replace = TRUE)
    datj <-  dat[indb1,]
    L <- tibble(L = datj$L)
    result[j,1] <- psi.hat(datj$Y,datj$A,L=c(), subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE)
    result[j,2] <- psi.hat(datj$Y,datj$A,L, subset = NULL, out.bin = FALSE, exp.bin = FALSE, exp.scalar = TRUE)
  }
  result_cc2[i,2] <-   sd(exp(result[,1]))
  result_cc2[i,4] <-   sd(exp(result[,2]))
}

res_cc2 <- as.data.frame(result_cc2[,1:4])

colnames(res_cc2) <- c("point","sd","point_L","sd_L")
res_cc2 <- res_cc2 %>% 
  mutate(
    ci_low    = point - 1.96*sd,
    ci_high   = point + 1.96*sd,
    ci_low_L  = point_L - 1.96*sd_L,
    ci_high_L = point_L + 1.96*sd_L
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

table_cc2 <- tibble(
  noL <- c(sum(res_cc2$contain)/nrow(res_cc2)),
  L <- c(sum(res_cc2$contain_L)/nrow(res_cc2))
  )

knitr::kable(table_cc2,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Continuous Outcome to Continuous Exposure"
             ) 
```

## (3) outcome: binary, exposure: continuous
```{r}
# z <- rnorm(1000)
# y <- c_to_b(-2*z,1000)
# x <- 2*z + rnorm(1000)
# psi.hat(y,x, subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE)
# z <- as.matrix(tibble(z))
# psi.hat(y,x,z, subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE)
result_bc <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  z <- rnorm(1000)
  y <- c_to_b(-2*z,1000)
  x <- 2*z + rnorm(1000)
  
  dat <- tibble(
    z = z,
    y = y,
    x = x
  )
  # summary(glm(y~x+z,data=dat))
  # summary(glm(y~x,data=dat))
  z <- tibble(z= dat$z)
  result_bc[i,1] <- exp(psi.hat(dat$y,dat$x,L=c(), subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE))
  result_bc[i,3] <- exp(psi.hat(dat$y,dat$x,z, subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE))
  result <- matrix(ncol = 2,nrow = nboots)
  for (j in 1:nboots) {
     n <- dim(dat)[1]
     set.seed(j)
     indb1 <- sample(1:n, size = n, replace = TRUE)
     datj <-  dat[indb1,]
     z <- tibble(z= datj$z)
     result[j,1] <- psi.hat(datj$y,datj$x,L=c(), subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE)
     result[j,2] <- psi.hat(datj$y,datj$x,z, subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE)
  }
  result_bc[i,2] <-   sd(exp(result[,1]))
  result_bc[i,4] <-   sd(exp(result[,2]))
}

res_bc <- as.data.frame(result_bc)

colnames(res_bc) <- c("point","sd","point_L","sd_L")
res_bc <- res_bc %>% 
  mutate(
    ci_low     = point - 1.96*sd,
    ci_high    = point + 1.96*sd,
    ci_low_L   = point_L - 1.96*sd_L,
    ci_high_L  = point_L + 1.96*sd_L
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )
  
table_bc <- tibble(
  noL <- c(sum(res_bc$contain)/nrow(res_bc)),
  L <- c(sum(res_bc$contain_L)/nrow(res_bc))
  )

  

knitr::kable(table_bc,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Binary Outcome to Continuous Exposure"
             )



```

```{r}
result_bc2 <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  L.true <- rbinom(n,1,0.5) ## L.true <- cbind(L.true,rep(0,N))
  Z <- 0.5 + 0.5*L.true
  pr <- 1/(1+exp(-Z))
  Y.true <- rbinom(n,1,pr)
  A.true <- 2*Z + rnorm(n)
  dat <- tibble(
    L = L.true,
    Y = Y.true,
    A = A.true
  )
  # summary(glm(Y~A+L,data=dat))
  # summary(glm(Y~A,data=dat))
  L <- tibble(L = dat$L)
  result_bc2[i,1] <- exp(psi.hat(dat$Y,dat$A,L=c(), subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE))
  result_bc2[i,3] <- exp(psi.hat(dat$Y,dat$A,L, subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE))
  result <- matrix(ncol = 2,nrow = nboots)
  for (j in 1:nboots) {
    n <- dim(dat)[1]
    set.seed(j)
    indb1 <- sample(1:n, size = n, replace = TRUE)
    datj <-  dat[indb1,]
    L <- tibble(L = datj$L)
    result[j,1] <- psi.hat(datj$Y,datj$A,L=c(), subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE)
    result[j,2] <- psi.hat(datj$Y,datj$A,L, subset = NULL, out.bin = TRUE, exp.bin = FALSE, exp.scalar = TRUE)
  }
  result_bc2[i,2] <- sd(exp(result[,1]))
  result_bc2[i,4] <- sd(exp(result[,2]))
}

res_bc2 <- as.data.frame(result_bc2[,1:4])

colnames(res_bc2) <- c("point","sd","point_L","sd_L")
res_bc2 <- res_bc2 %>% 
  mutate(
    ci_low    = point - 1.96*sd,
    ci_high   = point + 1.96*sd,
    ci_low_L  = point_L - 1.96*sd_L,
    ci_high_L = point_L + 1.96*sd_L
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

result_bc2 <- tibble(
  noL <- c(sum(res_bc2$contain)/nrow(res_bc2)),
  L <- c(sum(res_bc2$contain_L)/nrow(res_bc2))
  )

knitr::kable(result_bc2,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Binary Outcome to Continuous Exposure"
             ) 
```


## (4)  outcome: binary, exposure: binary
```{r message=FALSE,warning=FALSE}
result_bb <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
   
      set.seed(i)
      z <- rnorm(1000)
      y <- c_to_b(3*z,1000)
      x <- c_to_b(-2*z,1000)
      
      dat <- tibble(
        z = z,
        y = y,
        x = x
      )
        # summary(glm(y~x+z,data=dat))
        # summary(glm(y~x,data=dat))
      z <- tibble(z= dat$z)
       tryCatch(
           {
      result_bb[i,1] <- exp(psi.hat(dat$y,dat$x,L=c(), subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE))
      result_bb[i,3] <- exp(psi.hat(dat$y,dat$x,L=z, subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE))
           }, error=function(e){})
      result <- matrix(ncol = 2,nrow = nboots)
      for (j in 1:nboots) {
      
         n <- dim(dat)[1]
         set.seed(j)
         indb1 <- sample(1:n, size = n, replace = TRUE)
         datj <-  dat[indb1,]
         z <- tibble(z= datj$z)
         tryCatch(
           {
         result[j,1] <- psi.hat(datj$y,datj$x,L=c(), subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE)
         result[j,2] <- psi.hat(datj$y,datj$x,L=z, subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE)
      }, error=function(e){})
    }

  result_bb[i,2] <- sd(exp(result[,1]),na.rm = TRUE)
  result_bb[i,4] <- sd(exp(result[,2]),na.rm = TRUE)
}

res_bb <- as.data.frame(result_bb) %>% 
  drop_na()

colnames(res_bb) <- c("point","sd","point_L","sd_L")
res_bb <- res_bb %>% 
  mutate(
    ci_low     = point - 1.96*sd,
    ci_high    = point + 1.96*sd,
    ci_low_L   = point_L - 1.96*sd_L,
    ci_high_L  = point_L + 1.96*sd_L,
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

table_bb <- tibble(
  noL <- c(sum(res_bb$contain)/nrow(res_bb)),
  L <- c(sum(res_bb$contain_L)/nrow(res_bb))
  )

  

knitr::kable(table_bb,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Binary Outcome to Binary Exposure"
             ) 
  


```



Easy way
```{r}
result_bb2 <- matrix(ncol = 4,nrow = nsample)
for (i in 1:nsample) {
  set.seed(i)
  L.true <- rbinom(n,1,0.5) ## L.true <- cbind(L.true,rep(0,N))
  Z <- 0.5 + 0.5*L.true
  pr <- 1/(1+exp(-Z))
  Y.true <- rbinom(n,1,pr)
  A.true <- rbinom(n,1,pr)
  dat <- tibble(
    L = L.true,
    Y = Y.true,
    A = A.true
  )
  # summary(glm(Y~A+L,data=dat))
  # summary(glm(Y~A,data=dat))
  L <- tibble(L = dat$L)
  result_bb2[i,1] <- exp(psi.hat(dat$Y,dat$A,L=c(), subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE))
  result_bb2[i,3] <- exp(psi.hat(dat$Y,dat$A,L, subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE))
  result <- matrix(ncol = 2,nrow = nboots)
  for (j in 1:nboots) {
    n <- dim(dat)[1]
    set.seed(j)
    indb1 <- sample(1:n, size = n, replace = TRUE)
    datj <-  dat[indb1,]
    L <- tibble(L = datj$L)
    result[j,1] <- psi.hat(datj$Y,datj$A,L=c(), subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE)
    result[j,2] <- psi.hat(datj$Y,datj$A,L, subset = NULL, out.bin = TRUE, exp.bin = TRUE, exp.scalar = TRUE)
  }
  result_bb2[i,2] <- sd(result[,1])
  result_bb2[i,4] <- sd(result[,2])
}

res_bb2 <- as.data.frame(result_bb2[,1:4])

colnames(res_bb2) <- c("point","sd","point_L","sd_L")
res_bb2 <- res_bb2 %>% 
  mutate(
    ci_low    = point - 1.96*sd,
    ci_high   = point + 1.96*sd,
    ci_low_L  = point_L - 1.96*sd_L,
    ci_high_L = point_L + 1.96*sd_L
  ) %>% 
  mutate(
    contain   = ifelse(ci_low < 1 & 1 < ci_high, 1, 0),
    contain_L = ifelse(ci_low_L < 1 & 1 < ci_high_L, 1, 0)
  ) %>% 
  select(
    ci_low,ci_high,ci_low_L,ci_high_L,contain,contain_L
  )

table_bb2 <- tibble(
  noL <- c(sum(res_bb2$contain)/nrow(res_bb2)),
  L <- c(sum(res_bb2$contain_L)/nrow(res_bb2))
  )

  

knitr::kable(table_bb2,
             format = "pipe",
             digits = 3,
             col.names = c("Coverage Rate","Coverage Rate Condition on L"),
             caption = "Result For Binary Outcome to Binary Exposure"
             ) 
```

